apiVersion: v1
kind: Service
metadata:  
  name: clusterip-service
  labels:
    app: guestbook
    tier: frontend
spec:
  selector:    
    app: guestbook
    tier: frontend
  type: ClusterIP
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
